name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          registry-url: 'https://registry.npmjs.org/'
          scope: '@medrivia'
      - run: bun i # install
      - run: bun b # build
      - name: Remove GitHub alerts from README.md for NPM
        run: sed -i -r '/^>\s+\[!\w+\]/d' ./README.md # 
      - name: 'Use `exports` from publishConfig'
        run: |
          jq \
            'reduce .publishConfig as $in (.; . + $in) | del(.publishConfig)' \
            package.json > package.json~
          mv package.json~ package.json
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: 'https://registry.npmjs.org/'
          scope: '@medrivia'
      - name: 'Publish to NPM: `serai`'
        if: ${{ !github.event.release.prerelease }}
        run: npm publish --provenance --access public
        env:
          NPM_CONFIG_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: 'Publish to NPM: `serai` (next)'
        if: ${{ github.event.release.prerelease }}
        run: npm publish --provenance --access public --tag next
        env:
          NPM_CONFIG_TOKEN: ${{secrets.NPM_TOKEN}}
